// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL07kyPgo0I-F7V4VGbDfgdBszBt20ryk',
    appId: '1:993449836050:web:c2519fd0deae0b446962cb',
    messagingSenderId: '993449836050',
    projectId: 'buildup-bc163',
    authDomain: 'buildup-bc163.firebaseapp.com',
    storageBucket: 'buildup-bc163.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX_KKboQkhmf-hdGE4aGYSsPyolnRTZhY',
    appId: '1:993449836050:android:b33470e4bac87a486962cb',
    messagingSenderId: '993449836050',
    projectId: 'buildup-bc163',
    storageBucket: 'buildup-bc163.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaj7J5nElxCtUnSxo431GFp_dG9VJEkv8',
    appId: '1:993449836050:ios:a2a7a290985e0e016962cb',
    messagingSenderId: '993449836050',
    projectId: 'buildup-bc163',
    storageBucket: 'buildup-bc163.firebasestorage.app',
    androidClientId: '993449836050-d664cbboj2iu6s7oeu87hjmr1dvsbne9.apps.googleusercontent.com',
    iosClientId: '993449836050-qmc4otq8j2bn02qo3guc91q2gu77if15.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaj7J5nElxCtUnSxo431GFp_dG9VJEkv8',
    appId: '1:993449836050:ios:a2a7a290985e0e016962cb',
    messagingSenderId: '993449836050',
    projectId: 'buildup-bc163',
    storageBucket: 'buildup-bc163.firebasestorage.app',
    androidClientId: '993449836050-d664cbboj2iu6s7oeu87hjmr1dvsbne9.apps.googleusercontent.com',
    iosClientId: '993449836050-qmc4otq8j2bn02qo3guc91q2gu77if15.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL07kyPgo0I-F7V4VGbDfgdBszBt20ryk',
    appId: '1:993449836050:web:e2367e2cc9ded0886962cb',
    messagingSenderId: '993449836050',
    projectId: 'buildup-bc163',
    authDomain: 'buildup-bc163.firebaseapp.com',
    storageBucket: 'buildup-bc163.firebasestorage.app',
  );

}